import type { User } from "@/types/user";

export const MOCK_APPLICANTS: User[] = [
  { id: 1, order: 1, userId: "user1", name: "김지원", experience: 3, part: "Frontend", status: "지원" },
  { id: 2, order: 1, userId: "user2", name: "이민호", experience: 5, part: "Frontend", status: "스크린콜" },
  { id: 3, order: 2, userId: "user3", name: "박서연", experience: 2, part: "Frontend", status: "지원" },
  { id: 4, order: 3, userId: "user4", name: "최현우", experience: 7, part: "Frontend", status: "지원" },
  { id: 5, order: 4, userId: "user5", name: "정다은", experience: 1, part: "Frontend", status: "지원" },
  { id: 6, order: 1, userId: "user6", name: "한지민", experience: 4, part: "Frontend", status: "1차 인터뷰" },
  { id: 7, order: 2, userId: "user7", name: "오세훈", experience: 6, part: "Frontend", status: "스크린콜" },
  { id: 8, order: 1, userId: "user8", name: "윤아름", experience: 3, part: "Frontend", status: "코딩테스트" },
  { id: 9, order: 1, userId: "user9", name: "홍길동", experience: 8, part: "Frontend", status: "2차 인터뷰" },
  { id: 10, order: 2, userId: "user10", name: "강민수", experience: 5, part: "Frontend", status: "2차 인터뷰" },

  { id: 11, order: 2, userId: "user11", name: "서지은", experience: 2, part: "Frontend", status: "코딩테스트" },
  { id: 12, order: 3, userId: "user12", name: "임재현", experience: 4, part: "Frontend", status: "코딩테스트" },
  { id: 13, order: 2, userId: "user13", name: "문채원", experience: 6, part: "Frontend", status: "1차 인터뷰" },
  { id: 14, order: 3, userId: "user14", name: "조현준", experience: 7, part: "Frontend", status: "1차 인터뷰" },
  { id: 15, order: 3, userId: "user15", name: "백수진", experience: 3, part: "Frontend", status: "스크린콜" },
  { id: 16, order: 3, userId: "user16", name: "정우성", experience: 9, part: "Frontend", status: "2차 인터뷰" },
  { id: 17, order: 5, userId: "user17", name: "신예린", experience: 1, part: "Frontend", status: "지원" },
  { id: 18, order: 1, userId: "user18", name: "차은호", experience: 10, part: "Frontend", status: "최종 협의" },
  { id: 19, order: 1, userId: "user19", name: "유하린", experience: 2, part: "Frontend", status: "입사 확정" },
  { id: 20, order: 2, userId: "user20", name: "김정식", experience: 2, part: "Frontend", status: "입사 확정" },

  { id: 21, order: 6, userId: "user21", name: "김도윤", experience: 1, part: "Frontend", status: "지원" },
  { id: 22, order: 7, userId: "user22", name: "이서준", experience: 2, part: "Frontend", status: "지원" },
  { id: 23, order: 8, userId: "user23", name: "박지후", experience: 3, part: "Frontend", status: "지원" },
  { id: 24, order: 9, userId: "user24", name: "최민재", experience: 4, part: "Frontend", status: "지원" },
  { id: 25, order: 10, userId: "user25", name: "정현수", experience: 5, part: "Frontend", status: "지원" },
  { id: 26, order: 11, userId: "user26", name: "한유진", experience: 1, part: "Frontend", status: "지원" },
  { id: 27, order: 12, userId: "user27", name: "오지훈", experience: 2, part: "Frontend", status: "지원" },
  { id: 28, order: 13, userId: "user28", name: "윤서연", experience: 3, part: "Frontend", status: "지원" },
  { id: 29, order: 14, userId: "user29", name: "신동현", experience: 4, part: "Frontend", status: "지원" },
  { id: 30, order: 15, userId: "user30", name: "배지민", experience: 5, part: "Frontend", status: "지원" },

  { id: 31, order: 16, userId: "user31", name: "조민서", experience: 1, part: "Frontend", status: "지원" },
  { id: 32, order: 17, userId: "user32", name: "강태윤", experience: 2, part: "Frontend", status: "지원" },
  { id: 33, order: 18, userId: "user33", name: "서하늘", experience: 3, part: "Frontend", status: "지원" },
  { id: 34, order: 19, userId: "user34", name: "임성훈", experience: 4, part: "Frontend", status: "지원" },
  { id: 35, order: 20, userId: "user35", name: "문지우", experience: 5, part: "Frontend", status: "지원" },
  { id: 36, order: 21, userId: "user36", name: "차민혁", experience: 1, part: "Frontend", status: "지원" },
  { id: 37, order: 22, userId: "user37", name: "노윤아", experience: 2, part: "Frontend", status: "지원" },
  { id: 38, order: 23, userId: "user38", name: "백승현", experience: 3, part: "Frontend", status: "지원" },
  { id: 39, order: 24, userId: "user39", name: "유다인", experience: 4, part: "Frontend", status: "지원" },
  { id: 40, order: 25, userId: "user40", name: "장우진", experience: 5, part: "Frontend", status: "지원" },

  { id: 41, order: 26, userId: "user41", name: "홍세진", experience: 1, part: "Frontend", status: "지원" },
  { id: 42, order: 27, userId: "user42", name: "정하린", experience: 2, part: "Frontend", status: "지원" },
  { id: 43, order: 28, userId: "user43", name: "김태현", experience: 3, part: "Frontend", status: "지원" },
  { id: 44, order: 29, userId: "user44", name: "이수민", experience: 4, part: "Frontend", status: "지원" },
  { id: 45, order: 30, userId: "user45", name: "박준영", experience: 5, part: "Frontend", status: "지원" },
  { id: 46, order: 31, userId: "user46", name: "최은지", experience: 1, part: "Frontend", status: "지원" },
  { id: 47, order: 32, userId: "user47", name: "오현석", experience: 2, part: "Frontend", status: "지원" },
  { id: 48, order: 33, userId: "user48", name: "윤지후", experience: 3, part: "Frontend", status: "지원" },
  { id: 49, order: 34, userId: "user49", name: "신채원", experience: 4, part: "Frontend", status: "지원" },
  { id: 50, order: 35, userId: "user50", name: "배성훈", experience: 5, part: "Frontend", status: "지원" },
];
